Hungarian instance domain update
openfoodfoundation/ofn-install pull request #870
Opened 2023-04-07 17:36 UTC by pragai

2023-04-14 03:54 UTC, mkllnk requested changes

2023-04-14 03:54 UTC, mkllnk commented on inventory/host_vars/openfoodnetwork.hu/config.yml
You have to rename the name of the folder as well.

2023-05-04 08:59 UTC, pragai commented
Created requested changes, renamed folder.

2023-05-05 03:32 UTC, mkllnk approved these changes
This is looking good to me.

2023-05-16 09:20 UTC, jibees approved these changes
I'm not that comfortable with this part of the code, but looks good to me as well. 

Wondering what are the next steps? Should we synchronize the merging/provisioning of this PR to another task?

2023-05-17 02:26 UTC, mkllnk commented
> Wondering what are the next steps? Should we synchronize the merging/provisioning of this PR to another task?

Hungary is in the managed instances. So we should provision this. But maybe good to arrange a date with @pragai. When would it suit you to switch domains?

2023-05-17 21:16 UTC, pragai commented
Hi, please do the merge whenever suits you. We are in the kickoff process of boarding the instance, so it is a good time to change the domain now. Thanks!

2023-05-19 01:35 UTC, merged

2023-05-19 01:36 UTC, mkllnk commented
Okay, it's merged. Shall we proceed with provisioning or are you doing that?

2023-05-25 15:19 UTC, pragai commented
I!ll gladly do that.  Is it simply: ansible-playbook playbooks/provision.yml --limit=hu-prod ?

2023-05-25 22:53 UTC, mkllnk commented
Almost. You just need the secrets as well. Hm, I'm just realising that we added the n8n and Metabase integration to your instance via the secrets. If you don't need those then you can just go ahead. Otherwise, I need to share the new file with you or I just do the provisioning.