Update name of multi_redis repository
openfoodfoundation/ofn-install pull request #897
Opened 2023-10-02 02:54 UTC by mkllnk

Matt changed the underscore to a dash and downloading the role failed.

```
- downloading role 'multi_redis', owned by libre_ops
- downloading role from https://github.com/libre_ops/multi_redis/archive/1.0.1.tar.gz
Error: ]: failed to download the file: HTTP Error 404: Not Found
Warning: : - libre_ops.multi_redis was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
https://github.com/openfoodfoundation/ofn-install/actions/runs/6374617784/job/17299450784

2023-10-04 03:44 UTC, dacook approved these changes

2023-10-04 03:45 UTC, dacook commented
But I guess this is why he changed it...

```
ERROR! the role 'libre_ops.multi_redis' was not found in /home/runner/work/ofn-install/ofn-install/tests/../playbooks/roles:/home/runner/work/ofn-install/ofn-install/community:/home/runner/work/ofn-install/ofn-install/roles:/home/runner/work/ofn-install/ofn-install/tests/../playbooks

The error appears to be in '/home/runner/work/ofn-install/ofn-install/playbooks/provision.yml': line 70, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - role: libre_ops.multi_redis
      ^ here
```
https://github.com/openfoodfoundation/ofn-install/actions/runs/6375402638/job/17301125218?pr=897

2023-10-04 03:46 UTC, dacook requested changes
This doesn't fix it :(

2023-10-04 04:03 UTC, mkllnk commented
> This doesn't fix it :(

Oh, it fixes the installation and linting. But I need to add another change.

2023-10-04 04:25 UTC, dacook approved these changes
On to the next step :)

```
Unable to correct problems, you have held broken packages.

Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\n
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libgd-dev : Depends: libgd3 (= 2.2.5-5.2ubuntu2.1) but 2.3.3-9+ubuntu20.04.1+deb.sury.org+1 is to be installed
```

2023-10-04 21:55 UTC, mkllnk commented
> On to the next step :)

Yes, same problem as before. The GH Actions image seems to be in a different state to our standard Ubuntu images. So we could try to fiddle with the installed packages or spin up our own container...

2023-10-04 21:56 UTC, merged

2023-10-06 06:47 UTC, sigmundpetersen commented
Maybe some inspiration to get from this similar issue https://github.com/actions/runner-images/issues/2139
Looks like adding a workaround of cleaning the dependencies before reinstalling libgd-dev

2023-10-08 22:27 UTC, mkllnk commented
> Maybe some inspiration to get from this similar issue https://github.com/actions/runner-images/issues/2139
> Looks like adding a workaround of cleaning the dependencies before reinstalling libgd-dev

Ah, yes, I came to the same workaround. It works but a running build then revealed a bug in our setup. I'm still working on that one.